### ISSUE TITLE
几个问题 

### ISSUE THREAD

**Issue by dacelee** [MOACChain/FileStorm#5]
1.首先公测期间是否需要在http://www.filestorm.info/#/home上注册参与挖矿
2.根据FileStormUserGuide.md生成的SCSID，已经存入moac但是 http://www.filestorm.info在注册参与挖矿时还是提示墨客余额不足
so 换了方式,根据说明在 登录账号存入墨客,但是登入账号在转入墨客后还是确认不到账,并提示墨客不足
3.是否需要静态ip？
4.根据公测脚本开启SCS服务后,并检测运行状态,显示智能合约地址是:0x00000000000000000?

**Comment by inspirelife** [comment]
根据我的经验，回答一下2：公测是在测试网，你当作主网了，我也一样，估计很多人也是。
这么简单的事情，整个说明文档只有一处暗示了这点，却会给参与者带来很大麻烦。
解决方法：参与挖矿页面右下角有个链接，可以获得测试网的测试币，不需要我们转什么账。

**Comment by dacelee** [comment]
已解决
